CREATE TABLE IF NOT EXISTS todos (
	id INT AUTO_INCREMENT,
	user_id INT NOT NULL,
	title VARCHAR(256) NOT NULL,
	content VARCHAR(256) NOT NULL,
	createdAt DATETIME DEFAULT NOW(),
	updatedAt DATETIME DEFAULT NOW(),
	done TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
);
