version: "3.8"

services:
  my-mysql:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "33306:3306"
    env_file: ./.env
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      retries: 10

  todolist-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-api
    ports:
      - "11451:11451"
    depends_on:
      my-mysql:
        condition: service_healthy
    env_file: ./.env
    restart: on-failure